services:
  - type: web
    name: dry-route
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        generateValue: false
